version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  vault_auth:
    docker:
      - image: joatmon08/circleci-gcp-agent:287.0-1.14.72
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV 
            echo $VAULT_ROLE_ID > vault/role-id
            echo $VAULT_SECRET_ID	> vault/secret-id
            vault agent -config=vault/agent.hcl
            source vault/dockerhub
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG
      # - persist_to_workspace:
      #     root: ~/project/vault
      #       # Must be relative path from root
      #     paths:
      #       - dockerhub
  kubeconfig:
    docker:
      - image: joatmon08/circleci-gcp-agent:287.0-1.14.72
    steps:
      - run:
          name: Authenticate to Vault
          command: echo "vault"
      - run:
          name: Authenticate to GCP
          command: |
            gcloud auth activate-service-account --key-file=/tmp/service-account
            gcloud config set project $(cat /tmp/gcp-project)
            gcloud container clusters get-credentials $(cat /tmp/kubernetes-cluster) --zone $(cat /tmp/kubernetes-cluster-zone)
      - persist_to_workspace:
          root: /root/.kube
          paths:
            - config

workflows:
  build_test:
    jobs:
      - run_tests
      - vault_auth
