version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  build_docker_image:
    docker:
      - image: circleci/node:12
    environment:
      CIRCLE_PIPELINE_ID: << pipeline.number >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            export TAG=0.2.${CIRCLE_PIPELINE_ID}
            export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME
  create_gke_cluster:
    docker:
      - image: ariv3ra/terraform-gcp:latest
    environment:
      CLOUDSDK_CORE_PROJECT: cicd-workshops      
    steps:
      - checkout
      - run:
          name: Create GKE Cluster
          command: |
            echo $TF_CLOUD_TOKEN | base64 -d > $HOME/.terraformrc
            echo $GOOGLE_CLOUD_KEYS | base64 -d > $HOME/gcloud_keys
            gcloud auth activate-service-account --key-file ${HOME}/gcloud_keys
            cd terraform/gke_cluster/
            terraform init
            terraform plan -var credentials=$HOME/gcloud_keys -out=plan.txt
            terraform apply plan.txt
            gcloud container clusters get-credentials $(terraform output cluster) --zone="us-east1-d"
      - run:
         name: Deploy Application
         command: |
            cd terraform/kubernetes
            terraform init
            export TAG=0.2.<< pipeline.number >>
            export DOCKER_IMAGE="docker-image=${DOCKER_LOGIN}/${CIRCLE_PROJECT_REPONAME}:$TAG"
            terraform plan -var $DOCKER_IMAGE -out=plan.txt
            terraform apply plan.txt
            sleep 3m
            terraform destroy -var $DOCKER_IMAGE --auto-approve
            cd ../gke_cluster/
            terraform destroy --auto-approve
workflows:
  build_test:
    jobs:
      - run_tests
      - build_docker_image
      - create_gke_cluster:
          requires:
            - run_tests
            - build_docker_image
      # - approve-destroy:
      #     type: approval
      #     requires:
      #       - create_gke_cluster
      # - destroy_cluster